version: "3"
services:
  borgmatic:
    stop_grace_period: 1m30s
    build: .
    env_file: .env
    volumes:
      - /data:/mnt/source
      - ./data/ssh:/root/.ssh
      - ./data/borgmatic.d:/etc/borgmatic.d
      - ./data/.config/borg:/root/.config/borg
      - ./data/.cache/borg:/root/.cache/borg
