version: "3"
services:
  borgmatic:
    image: leononame/borgmatic:latest
    env_file: .env
    volumes:
      - /mnt/data:/mnt/source:ro
      - ./data/ssh:/root/.ssh
      - ./data/borgmatic.d:/etc/borgmatic.d
      - ./data/.config/borg:/root/.config/borg
      - ./data/.cache/borg:/root/.cache/borg
